consul:
  image: progrium/consul
  hostname: consul
  ports:
    - "8300:8300"
    - "8301:8301"
    - "8301:8301/udp"    
    - "8302:8302"
    - "8302:8302/udp"
    - "8400:8400"
    - "8500:8500"
  command: "-server -bootstrap"
  volumes:
    - /data
    - /tmp
