nginx:
  image: nginx:1.9.9
  hostname: nginx
  restart: always
  ports:
    - "80:80"
    - "443:443"
  volumes:
    - ./etc:/etc/nginx
    - ./html:/usr/share/nginx/html
    - ./log:/var/log/nginx
    - ./www:/www
